from .corba_wrapper import CCREG_MODULE, FILEMANAGER, LOGGER, PUBLIC_REQUEST, REGISTRY_MODULE, WHOIS

__all__ = ['CCREG_MODULE', 'FILEMANAGER', 'LOGGER', 'PUBLIC_REQUEST', 'REGISTRY_MODULE', 'WHOIS']
